# -*- coding: utf-8 -*-
"""Meu_Projeto_BigQuery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Marianaoliveiranalysis/An-lise-Ecommerce-Smurfette-/blob/main/Meu_Projeto_BigQuery.ipynb
"""

!pip install pandas-gbq --quiet

import pandas as pd

from pandas_gbq import read_gbq

from google.colab import auth
auth.authenticate_user()

import sqlite3

query = """
    SELECT *
    FROM bigquery-public-data.austin_bikeshare.bikeshare_trips
    LIMIT 1000
"""
df = read_gbq(query, project_id='meu-projeto-ebac', dialect='standard')

df.head()

df.isnull().sum()

df.describe()

df.info()

df['subscriber_type'].value_counts()

#Quais estações de origem mais populares?

from pandas_gbq import read_gbq
 query = """
SELECT  start_station_name, COUNT(trip_id) AS total_
FROM bigquery-public-data.austin_bikeshare.bikeshare_trips
WHERE start_station_name IS NOT NULL
GROUP BY start_station_name
ORDER BY COUNT(trip_id) DESC
LIMIT 3
"""
df = read_gbq(query, project_id='meu-projeto-ebac', dialect='standard')

print(df)           # imprime tudo
df.head()           # mostra as 5 primeiras linhas (mais organizado no Colab)

import matplotlib.pyplot as plt

# Define tamanho do gráfico
plt.figure(figsize=(8,5))

# Cria gráfico de barras horizontais
plt.barh(df["start_station_name"], df["total_"], color="skyblue")

# Inverte a ordem para mostrar a mais popular no topo
plt.gca().invert_yaxis()

# Títulos e labels
plt.title("Top 3 Estações de Origem Mais Populares", fontsize=14, weight="bold")
plt.xlabel("Total de Viagens")
plt.ylabel("Estação de Origem")

# Mostra valores em cima das barras
for index, value in enumerate(df["total_"]):
    plt.text(value, index, str(value))

# Exibe o gráfico
plt.show()

# Quais tipos de usuários mais utilizam as bicicletas?

from pandas_gbq import read_gbq
query = """
SELECT subscriber_type, COUNT(trip_id) AS total_
FROM bigquery-public-data.austin_bikeshare.bikeshare_trips
WHERE subscriber_type IS NOT NULL
GROUP BY subscriber_type
ORDER BY COUNT(trip_id) DESC
LIMIT 5

"""
df = read_gbq(query, project_id='meu-projeto-ebac', dialect='standard')
print(df)           # imprime tudo
df.head()           # mostra as 5 primeiras linhas

import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.barplot(data=df, x="subscriber_type", y="total_", palette="Blues_d")

plt.title("Top 3 Tipos de Usuários que Mais Utilizam as Bicicletas", fontsize=14)
plt.xlabel("Tipo de Usuário")
plt.ylabel("Total de Viagens")

# Rotacionar rótulos do eixo X
plt.xticks(rotation=30, ha='right')

# Mostrar valores em cima das barras
for i, v in enumerate(df["total_"]):
    plt.text(i, v + 100, str(v), ha='center', fontsize=10)

plt.show()



# Tempo médio de duração das viagens?

from pandas_gbq import read_gbq

query = """
SELECT
  AVG(duration_minutes) AS tempo_medio_minutos,
  COUNT(trip_id) AS total_viagens
FROM
  `bigquery-public-data.austin_bikeshare.bikeshare_trips`
WHERE duration_minutes IS NOT NULL
"""

df = read_gbq(query, project_id='meu-projeto-ebac', dialect='standard')
print(df)

# Qual o tipo de bicicleta é mais usada a clássica ou a eletrica nas viagens?
from pandas_gbq import read_gbq

query = """
SELECT
  bike_type,
  COUNT(trip_id) AS total_viagens
FROM
  `bigquery-public-data.austin_bikeshare.bikeshare_trips`
WHERE bike_type IS NOT NULL
GROUP BY bike_type
"""

df = read_gbq(query, project_id='meu-projeto-ebac', dialect='standard')
print(df)

